In [1]:
import pandas as pd

Welding_Log_Df = pd.read_excel("./welding_Log_Dataset.xlsx")
Welding_Log_Df.head()

,ISO_N,REV,LINE_NBR,Zone,Joint_N,LINE_CLASS,Joint_Type,Thickness,Diameter,WPS,...,Fit-Up_Date,VT,Vt_Date,PT,Pt_Date,Paut_Report,Paut_Result,Paut_Date,RT,Rt_Date
0,ZA38180-PCS-AM-B10-101-E10-000-01,NaN,400-AM-B10-101-CD2,ZONE 10,FW-01,CD2,BW,9.53,400,04/24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ZA38180-PCS-AM-B10-101-E10-000-01,0.0,400-AM-B10-101-CD2,ZONE 10,SW-01,CD2,BW,9.53,400,04/24,...,45938,VT-0005,45944,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ZA38180-PCS-AM-B10-101-E10-000-01,0.0,400-AM-B10-101-CD2,ZONE 10,SW-02,CD2,BW,9.53,400,04/24,...,45961,VT-0040,46013,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ZA38180-PCS-AM-B10-101-E10-000-01,NaN,400-AM-B10-101-CD2,ZONE 10,SW-03,CD2,BW,9.53,400,04/24,...,46181,VT-102,46181,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ZA38180-PCS-AM-B10-101-E10-000-01,NaN,400-AM-B10-101-CD2,ZONE 10,SW-04,CD2,BW,9.53,400,04/24,...,46181,VT-102,46181,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
Welding_Log_Df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2852 entries, 0 to 2851
Data columns (total 28 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ISO_N          2852 non-null   str
 1   REV            1214 non-null   float64
 2   LINE_NBR       2852 non-null   str
 3   Zone           2852 non-null   str
 4   Joint_N        2852 non-null   str
 5   LINE_CLASS     2850 non-null   str
 6   Joint_Type     2850 non-null   object
 7   Thickness      2850 non-null   object
 8   Diameter       2850 non-null   object
 9   WPS            2850 non-null   str
 10  Base Met       2850 non-null   str
 11  Filler_Metal   2850 non-null   str
 12  Electrode      2850 non-null   str
 13  Process        2850 non-null   str
 14  Welding_Date   1387 non-null   object
 15  Welder_ID_One  1405 non-null   str
 16  Welder_ID_Two  76 non-null     str
 17  fit-up         1385 non-null   str
 18  Fit-Up_Date    1385 non-null   object
 19  VT             1386 non-null   str
 20  Vt_Date        1386 non-null   object
 21  PT             161 non-null    str
 22  Pt_Date        46 non-null     object
 23  Paut_Report    231 non-null    str
 24  Paut_Result    244 non-null    str
 25  Paut_Date      244 non-null    float64
 26  RT             0 non-null      float64
 27  Rt_Date        0 non-null      float64
dtypes: float64(4), object(7), str(17)
memory usage: 624.0+ KB

In [3]:
Welding_Log_Df.columns

Index(['ISO_N', 'REV', 'LINE_NBR ', 'Zone', 'Joint_N', 'LINE_CLASS',
       'Joint_Type', 'Thickness', 'Diameter', 'WPS', 'Base Met ',
       'Filler_Metal', 'Electrode', 'Process', 'Welding_Date', 'Welder_ID_One',
       'Welder_ID_Two', 'fit-up', 'Fit-Up_Date', 'VT', 'Vt_Date', 'PT',
       'Pt_Date', 'Paut_Report', 'Paut_Result', 'Paut_Date', 'RT', 'Rt_Date'],
      dtype='str')

In [4]:
Welding_Log_Df.columns = (
    Welding_Log_Df.columns.str.strip().str.replace(" ", "_").str.replace("-", "_").str.title()
)

In [5]:
Welding_Log_Df.columns

Index(['Iso_N', 'Rev', 'Line_Nbr', 'Zone', 'Joint_N', 'Line_Class',
       'Joint_Type', 'Thickness', 'Diameter', 'Wps', 'Base_Met',
       'Filler_Metal', 'Electrode', 'Process', 'Welding_Date', 'Welder_Id_One',
       'Welder_Id_Two', 'Fit_Up', 'Fit_Up_Date', 'Vt', 'Vt_Date', 'Pt',
       'Pt_Date', 'Paut_Report', 'Paut_Result', 'Paut_Date', 'Rt', 'Rt_Date'],
      dtype='str')

In [6]:
Welding_Log_Df.dtypes

Iso_N                str
Rev              float64
Line_Nbr             str
Zone                 str
Joint_N              str
Line_Class           str
Joint_Type        object
Thickness         object
Diameter          object
Wps                  str
Base_Met             str
Filler_Metal         str
Electrode            str
Process              str
Welding_Date      object
Welder_Id_One        str
Welder_Id_Two        str
Fit_Up               str
Fit_Up_Date       object
Vt                   str
Vt_Date           object
Pt                   str
Pt_Date           object
Paut_Report          str
Paut_Result          str
Paut_Date        float64
Rt               float64
Rt_Date          float64
dtype: object

In [7]:
Welding_Log_Df["Diameter"].unique()

array([400, nan, 'FW-11'], dtype=object)

In [8]:
Welding_Log_Df["Diameter"] = Welding_Log_Df["Diameter"].replace('FW-11', 400).fillna(400)

In [9]:
Welding_Log_Df["Diameter"].unique()

array([400], dtype=object)

In [10]:
Welding_Log_Df["Diameter"] = Welding_Log_Df["Diameter"].astype(int)

In [11]:
df = Welding_Log_Df[Welding_Log_Df["Rev"].isnull()]
df.shape

(1638, 28)

In [12]:
Welding_Log_Df["Rev"] =  Welding_Log_Df["Rev"].fillna(0)
Welding_Log_Df["Rev"] = Welding_Log_Df["Rev"].astype(int)

In [13]:
Welding_Log_Df.columns

Index(['Iso_N', 'Rev', 'Line_Nbr', 'Zone', 'Joint_N', 'Line_Class',
       'Joint_Type', 'Thickness', 'Diameter', 'Wps', 'Base_Met',
       'Filler_Metal', 'Electrode', 'Process', 'Welding_Date', 'Welder_Id_One',
       'Welder_Id_Two', 'Fit_Up', 'Fit_Up_Date', 'Vt', 'Vt_Date', 'Pt',
       'Pt_Date', 'Paut_Report', 'Paut_Result', 'Paut_Date', 'Rt', 'Rt_Date'],
      dtype='str')

In [14]:

Welding_Log_Df["Line_Class"] = Welding_Log_Df["Line_Class"].fillna("CD2")

In [15]:
Welding_Log_Df[Welding_Log_Df["Joint_Type"] == "BW"].shape

(681, 28)

In [16]:
Welding_Log_Df["Joint_Type"].unique()

array(['BW', 'SW', nan, '9,53', 9.53, 'FW-9'], dtype=object)

In [17]:
Welding_Log_Df["Joint_Type"] = Welding_Log_Df["Joint_Type"].replace("FW-9", "FW").replace("9,53", "BW").replace(9.5,"BW").fillna("BW")

In [18]:
Welding_Log_Df["Joint_Type"].unique()

array(['BW', 'SW', 9.53, 'FW'], dtype=object)

In [19]:
df = Welding_Log_Df[Welding_Log_Df["Joint_Type"].isnull()]
df.head(10)

Empty DataFrame
Columns: [Iso_N, Rev, Line_Nbr, Zone, Joint_N, Line_Class, Joint_Type, Thickness, Diameter, Wps, Base_Met, Filler_Metal, Electrode, Process, Welding_Date, Welder_Id_One, Welder_Id_Two, Fit_Up, Fit_Up_Date, Vt, Vt_Date, Pt, Pt_Date, Paut_Report, Paut_Result, Paut_Date, Rt, Rt_Date]
Index: []

[0 rows x 28 columns]